JaiUneIdee\LocalisationBundle\Entity\Localisation:
  type: entity
  repositoryClass: JaiUneIdee\LocalisationBundle\Repository\LocalisationRepository
  table: localisation
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    nom:
      type: string
      lenght: 255
      notnull: true
    min:
      type: integer
      notnull: true
    max:
      type: integer
      notnull: true
    niveau:
      type: integer
      notnull: true
      options:
        default: 0
    population:
      type: integer
      notnull: true
      options:
        default: 0
    urlName:
      type: string
      lenght: 255
      nullable: true
      options:
        default: null
    footer:
      type: text
      nullable: true
      options:
        default: null
    css:
      type: string
      lenght: 255
      nullable: true
      options:
        default: null
  manyToOne:
    parent:
      targetEntity: Localisation
  lifecycleCallbacks: {  }